### ISSUE TITLE
Problem with mydomain.com/sku links...

### ISSUE THREAD

**Issue by Scarpace** [varunsridharan/sku-shortlink-for-woocommerce#2]
Is it possible to make this plugin work like this?

Original product URL:
http://www.mydomain.com/product/my-original-product-title-url

Original product SKU:
12345678

And with this plugin, have a URL like this shortlink work somehow?
http://www.mydomain.com/12345678

I can only get the shortlinks to work if I use a CUSTOM or additional word in the URL like:
http://www.mydomain.com/sku/12345678

So, this works...
http://www.mydomain.com/sku/12345678

But I need BOTH the original product URL and this shortlink to work, is that possible????
Original: http://www.mydomain.com/product/my-original-product-title-url
Shortlink: http://www.mydomain.com/12345678
(I the shortlink to work without "/sku" or anything else between mydomain.com/ and 12345678)

PLEASE HELP!!!

**Comment by technofreaky** [comment]
@Scarpace right now you cant have 2 options active at a time.

if you need more than 1 active . then i need to workaround. but which can be done only after 1 month. 

please do contact me via email : varunsridharan23@gmail.com

**Comment by Scarpace** [comment]
Thanks for your FAST reply!!!!

If I configure it to use /sku/%sku%/ then both the original and shortlink works at the sametime... like this:
http://www.mydomain.com/product/my-original-product-title-url  <--WORKS
http://www.mydomain.com/sku/12345678 <--WORKS

But, if I remove the /sku/ and just try to use %sku%...  only the shortlink works:
http://www.mydomain.com/product/my-original-product-title-url  <--DOES NOT WORK
http://www.mydomain.com/12345678 <--WORKS

How can I get it to work like this without the /sku/ folder??

**Comment by technofreaky** [comment]
Note sure why this dose not work.

just provide a screenshot of settings page. so i can check for the issue.

**Comment by Scarpace** [comment]
![untitled](https://cloud.githubusercontent.com/assets/22826878/19373067/b6afde42-9186-11e6-953f-b83a71d77150.jpg)

**Comment by technofreaky** [comment]
@Scarpace Ok thanks i will get back to you in a day,. in the mean time you 

if you change the sku settings. please do update permalink settings once. and check.

**Comment by Scarpace** [comment]
And with these settings, only the shortlink URL works like this...
http://www.mydomaintest.com/product/my-original-product-title-url <--DOES NOT WORK
http://www.mydomaintest.com/12345678 <--WORKS
![untitled2](https://cloud.githubusercontent.com/assets/22826878/19373250/36a014d6-9188-11e6-8247-e59a0214f251.jpg)

**Comment by Scarpace** [comment]
I just tried changing the permalinks and changing them back to default and still does not work right. Thanks for your help!!!
