### ISSUE TITLE
Version 1.3.4, – 1.3.5, broken permalinks

### ISSUE THREAD

**Issue by caballe** [varunsridharan/sku-shortlink-for-woocommerce#34]
Version 1.3.3.works perfectly, but 1.3.4 and 1.3.5 not work and also
broken the site permalinks, 404 error on all pages, even if I update the permalinks settings.

PHP Version : 7.3.10
MySQL Version : 5.5.5
Server Info : Apache
WP Version : 5.2.4
WooCommerce 3.7.1 

regards
Salvador

**Comment by raviramanna** [comment]
Yes same issue. Version 1.3.3 works but newer versions don't work. Why?
