### ISSUE TITLE
Link broken when sku is xx/yyy

### ISSUE THREAD

**Issue by juanpalmy** [varunsridharan/sku-shortlink-for-woocommerce#38]
Hi, 
I have a problem when sku of product is xx/yyy.
If sku is type xx/yyy, the generate url is broken.
Tks

**Comment by varunsridharan** [comment]
Hi There Sorry about the delayed response. can you please provide me with a realworld example ?

**Comment by juanpalmy** [comment]
Sure!
My URL format is : prodotto\/%sku%\/%postname%
My product is : 
Name : BOCCADAMO MYA BATUFFOLO COLLANA SCRIGNO APRIBILE
SKU : BT/GR12
Generated (**wrong**) URL is : https://xxx.it/prodotto/BT/GR12/boccadamo-mya-batuffolo-collana-scrigno-apribile/

If you try on your site with the information I told you, you can replicate the problem.

Tks

**Comment by juanpalmy** [comment]
@varunsridharan can you answer me?
You let me know if it's not possible.
Tks

**Comment by juanpalmy** [comment]
Fixed?
