### ISSUE TITLE
Upgrading To V1.0 Throws Fatal Error

### ISSUE THREAD

**Issue by caballe** [varunsridharan/sku-shortlink-for-woocommerce#6]
Hello,

I try to update the plugin, and I have the following error:

```
PHP Fatal error:  Interface 'WPO\Helper\Interfaces\Container' not found in wp-content/plugins/sku-shortlink-for-woocommerce/vendor/wponion/wponion/builder/helper/container/class-helper.php on line 17
```
regards
Salvador

**Comment by Sperovita** [comment]
Same
```
An error of type E_ERROR was caused in line 17 of the file /home/lmtproducts/public_html/wp-content/plugins/sku-shortlink-for-woocommerce/vendor/wponion/wponion/builder/helper/container/class-helper.php. 
Error message: Interface 'WPO\Helper\Interfaces\Container' not found
```

**Comment by varunsridharan** [comment]
@caballe @Sperovita Thanks for reporting the issue.

Can you please provide me with some more information. such as your hosting env ? php version and so on

if possible please provide me WooCommerce System report.

**Comment by caballe** [comment]
here is the info:

> WooCommerce version: 		3.6.2
> WordPress version: 		5.2	
> WordPress multisite: 		–
> WordPress memory limit: 	1 GB	
> Server info: 		     Apache
> PHP version: 		     7.3.5	
> PHP post max size: 		8 MB
> PHP time limit: 		0
> PHP max input vars: 		2000
> cURL version: 		7.29.0, NSS/3.36
> MySQL version: 		5.5.5-10.1.40-MariaDB	
> Max upload size: 		8 MB
> WooCommerce database version: 		3.6.0

Regards
Salvador

**Comment by varunsridharan** [comment]
@caballe thanks for the information. i did test with PHP V 7.3.5 but i am unable to replicate the same issue.
Can you please delete the plugin and reinstall it once again. 

As of now i am pushing an update V 1.1 to wordpress.org which will be up soon 
In V 1.1
* Added Support For PHP 5.6 
* Site Language (#7 Issue Fixed)

**Comment by caballe** [comment]
I deleted the plugin and install v 1.1, no success,  the error, still is the same  :-(

PHP Fatal error:  Interface 'WPO\Helper\Interfaces\Container
plugins/sku-shortlink-for-woocommerce/vendor/wponion/wponion/builder/helper/container/class-helper.php on line 17

**Comment by varunsridharan** [comment]
@caballe sorry about that. i just figured the issue and fixed it.

V 1.2 is a final version which includes a fix for it. please wait for few min a new update will be published in wordpress.org

**Comment by caballe** [comment]
Now it works perfectly, thank you very much.
best regards
Salvador
