### ISSUE TITLE
version 1.0 error in language

### ISSUE THREAD

**Issue by annonusser** [varunsridharan/sku-shortlink-for-woocommerce#7]
New version left me with woocommerce as english only, even after changing language back english then returning to the previous (spanish), this plugin forces the site to stay in english.

I tried deactivating the plugin, and the problem is solved.

**Comment by varunsridharan** [comment]
@annonusser thanks for letting me know. i will check for the issue and get it resolved asap

**Comment by varunsridharan** [comment]
Issue Fixed In V1.1
